"""
Constants

Taken from all over the PIPG
"""


# PIPG-37
NOM_PART_OBJ = 1
NOM_PART_SCADA = 2
NOM_PART_EVT = 3
NOM_PART_DIM = 4
NOM_PART_PGRP = 6
NOM_PART_INFRASTRUCT = 8


# PIPG-42
ROIV_APDU = 1
RORS_APDU = 2
ROER_APDU = 3
ROLRS_APDU = 5


# PIPG-47
CMD_EVENT_REPORT = 0
CMD_CONFIRMED_EVENT_REPORT = 1
CMD_GET = 3
CMD_SET = 4
CMD_CONFIRMED_SET = 5
CMD_CONFIRMED_ACTION = 7


# PIPG-45
NO_SUCH_OBJECT_CLASS = 0
NO_SUCH_OBJECT_INSTANCE = 1
ACCESS_DENIED = 2
GET_LIST_ERROR = 7
SET_LIST_ERROR = 8
NO_SUCH_ACTION = 9
PROCESSING_FAILURE = 10
INVALID_ARGUMENT_VALUE = 15
INVALID_SCOPE = 16
INVALID_OBJECT_INSTANCE = 17


NOM_POLL_PROFILE_SUPPORT = 1
NOM_DIM_DIMLESS = 512
NOM_DIM_PERCENT = 544
NOM_ATTR_GRP_METRIC_VAL_OBS = 2051
NOM_ATTR_NU_VAL_OBS = 2384
NOM_ATTR_TIME_STAMP_ABS = 2448
NOM_DIM_BEAT_PER_MIN = 2720
NOM_DIM_RESP_PER_MIN = 2784
NOM_ACT_POLL_MDIB_DATA = 3094
NOM_NOTI_MDS_CREAT = 3334
NOM_NOTI_CONN_INDIC = 3351
NOM_NOTI_MDS_CONNECT_INDIC = NOM_NOTI_CONN_INDIC  # These appear to be the same based on experimental data / PIPG-53
NOM_DEV_PULS_VMD = 5138
NOM_ECG_CARD_BEAT_RATE = 16770
NOM_ECG_V_P_C_CNT = 16993
NOM_PLETH_PULS_RATE = 18466
NOM_PULS_OXIM_PERF_REL = 19376
NOM_PULS_OXIM_SAT_O2 = 19384
NOM_RESP_RATE = 20490
NOM_ATTR_POLL_PROFILE_EXT = 61441
NOM_SAT_O2_TONE_FREQ = 61448
NOM_PRESS_BLD_NONINV_PULS_RATE = 61669
NOM_ATTR_NET_ADDR_INFO = 61696

ENUM_IDENTIFIERS = {
    NOM_POLL_PROFILE_SUPPORT: "NOM_POLL_PROFILE_SUPPORT",
    NOM_DIM_DIMLESS: "NOM_DIM_DIMLESS",
    NOM_DIM_PERCENT: "NOM_DIM_PERCENT",
    NOM_ATTR_GRP_METRIC_VAL_OBS: "NOM_ATTR_GRP_METRIC_VAL_OBS",
    NOM_ATTR_NU_VAL_OBS: "NOM_ATTR_NU_VAL_OBS",
    NOM_ATTR_TIME_STAMP_ABS: "NOM_ATTR_TIME_STAMP_ABS",
    NOM_DIM_BEAT_PER_MIN: "NOM_DIM_BEAT_PER_MIN",
    NOM_DIM_RESP_PER_MIN: "NOM_DIM_RESP_PER_MIN",
    NOM_ACT_POLL_MDIB_DATA: "NOM_ACT_POLL_MDIB_DATA",
    NOM_NOTI_MDS_CREAT: "NOM_NOTI_MDS_CREAT",
    NOM_NOTI_CONN_INDIC: "NOM_NOTI_CONN_INDIC",
    NOM_DEV_PULS_VMD: "NOM_DEV_PULS_VMD",
    NOM_ECG_CARD_BEAT_RATE: "NOM_ECG_CARD_BEAT_RATE",
    NOM_ECG_V_P_C_CNT: "NOM_ECG_V_P_C_CNT",
    NOM_PLETH_PULS_RATE: "NOM_PLETH_PULS_RATE",
    NOM_PULS_OXIM_PERF_REL: "NOM_PULS_OXIM_PERF_REL",
    NOM_PULS_OXIM_SAT_O2: "NOM_PULS_OXIM_SAT_O2",
    NOM_RESP_RATE: "NOM_RESP_RATE",
    NOM_ATTR_POLL_PROFILE_EXT: "NOM_ATTR_POLL_PROFILE_EXT",
    NOM_SAT_O2_TONE_FREQ: "NOM_SAT_O2_TONE_FREQ",
    NOM_PRESS_BLD_NONINV_PULS_RATE: "NOM_PRESS_BLD_NONINV_PULS_RATE",
    NOM_ATTR_NET_ADDR_INFO: "NOM_ATTR_NET_ADDR_INFO",
}

